[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pybann"
version = "0.1.0"
requires-python = ">=3.9"
authors = [{ name = "Damien Pageot", email = "damien.pageot+pybann@gmail.com" }]
description = "Python Basic Artificial Neural Network."
readme = "README.md"
license = { text = "MIT" }
classifiers=[
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]

dependencies = [
    "numpy",
    "tqdm",
    "build",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "isort",
    "flake8",
    "pytest-cov",
]

docs = [
    "mkdocs-material",
]

[project.urls]
Homepage = "https://github.com/pageotd/pybann"

[tool.setuptools]
package-dir = { "" = "src" }
packages = ["runmd"]
